### ISSUE TITLE
Parsing issues

### ISSUE THREAD

**Issue by mystygage** [mgifos/quick-plan#10]
I defined a workout with two repeats:

```
workout: 7x1k IV
- warmup: 2km @z2
- repeat: 3
 - run: 100m
 - recover: 1:00
- repeat: 7
 - run: 1000m @z5
 - recover: 400m
- recover: 2km @z2
- cooldown: lap-button
```

The first repeat is missing in Garmin Connect:

<img width="1037" alt="7x1k iv 2018-05-15 15-47-23" src="https://user-images.githubusercontent.com/1107406/40060637-629b2bb0-5857-11e8-83b9-7c2d8bd7cd73.png">

**Comment by mystygage** [comment]
I just stumbled upon another error. This workout:
```
workout: 12k @GA1-2 STL
- run: 12km @z4
- cooldown: lap-button
- repeat: 3
 - run: 100m
 - recover: 1:00
```
is translated to:
<img width="1031" alt="12k stl 2018-05-15 16-10-55" src="https://user-images.githubusercontent.com/1107406/40062067-a0579742-585a-11e8-951c-20f6ce41bef4.png">

The lap button press step was skipped.

**Comment by mgifos** [comment]
Hi, the second comment is related to the issue #8 and that is fixed. On the other hand I've tried to parse the sample from the original issue description and it went fine. It could be that you have special characters in your sample which we cannot see here. Can you send your sample in csv format and try to import it again with the latest release 0.2.2 - it could be that it's solved by solving the issue #8?

**Comment by mystygage** [comment]
Thanks!
With 0.2.2 it looks like this:
<img width="568" alt="garmin connect 2018-05-31 18-06-51" src="https://user-images.githubusercontent.com/1107406/40793731-850a1974-64fd-11e8-8cf9-824b76b2e4fd.png">

The lap-button is there, but the repeat step is missing... This is like the problem mentioned in the first comment. It looks like everything after cooldown with lap-button is skipped.

**Comment by mgifos** [comment]
Great, you decided to give a contribution! I'll take a look after my normal working hours and get back to this.
