### ISSUE TITLE
Feature Request - import bike and swim schedules

### ISSUE THREAD

**Issue by hmsnaith** [mgifos/quick-plan#13]
I would love to be able to use this to plan my triathlon training.
That means I need to create bike and swim schedules as well as run ones.

Is it in your plans to add that anytime soon?
H

**Comment by mgifos** [comment]
I'll take a look of how difficult is to support bikes and swimming workouts. Until then, the feature request can stay open.

**Comment by hmsnaith** [comment]
Thanks - is there a 'contribution' link. I think this is a great tool, well worth supporting

**Comment by mgifos** [comment]
The good news is that I've just bought a new MTB bike. So you can expect me to be more involved in the near future. On the other side a became a father a few weeks ago, so my spare time is not that wide any more.

**Comment by mgifos** [comment]
Cycling workouts are supported now. #16 in release 0.2.3
