### ISSUE TITLE
support min/mi paces

### ISSUE THREAD

**Issue by leingang** [mgifos/quick-plan#19]
First, let me say this is a cool project!  Thanks for getting it started.

I am from the USA and we keep paces in minutes per **mile**.  When I imported and scheduled a week of workouts, I noticed that my paces got interpreted as minutes per **kilometer**.

I notice that the grammar supports miles as a distance, but it seems only min/km as pace.    Could there be a way to support min/mi too?

  * For instance, if the duration is a distance in miles, the pace could be assumed to be in min/mi.
  * Or, the pace could accept a units suffix of `mpm` or `mpk` that would distinguish the two.
  * Maybe a command-line setting or configuration value that indicates your paces are to be interpreted as `mpm`

Thanks for considering.

**Comment by leingang** [comment]
Workaround: [convert](https://www.depicus.com/swim-bike-run/pace-conversion-chart) the pace in advance.

**Comment by mgifos** [comment]
Hi, thanks for your support.

I have just returned from a vacation. We'll figure something out when it comes to syntax of different pace units. Your suggestions sound reasonable to me, I like implicit command line config and explicit notation in CSV file. Maybe we can support it both. I'll get back to this soon.

**Comment by leingang** [comment]
Thanks! There is also a Garmin user preference for preferred distance units.  If that could be accessed by API, it might be the smoothest way.

**Comment by mgifos** [comment]
Do you know perhaps which endpoint of the API provides this?

**Comment by mgifos** [comment]
I investigated this and I couldn't find the API endpoint that provides this and that works, so we'll have to fallback to the initial suggestion - either to add unit of measure in the workout definitions or to add an additional config, or both.
