### ISSUE TITLE
Scheduling of previously defined workouts

### ISSUE THREAD

**Issue by leingang** [mgifos/quick-plan#20]
It seems like if I have a cell in my CSV file such as:

```
running: 8E
- run: 8mi
- cooldown: lap-button
```
and then a later cell with just `8E` in it, the expected effect is that the "8E" workout should be defined, then scheduled on both days.  The [Ultra 80k model CSV file](https://docs.google.com/spreadsheets/d/1b1ZzrAFrjd-kvPq11zlbE2bWn2IQmUy0lBqIOFjqbwk/edit#gid=0) has several repeated workout days like this (e.g., "8k jog" each Wednesday).

Instead, I get it scheduled on the day for which it's defined, but nothing gets scheduled on the later day.  Am I doing it wrong?

**Comment by mgifos** [comment]
Can you attach a complete CSV file to the issue, so I can test it myself?

**Comment by mystygage** [comment]
I had a similar issue with the training on first Wednesday here (6k @GA1/2+STL): https://docs.google.com/spreadsheets/d/1EXa9QL2AvyIkZIFI239Hf2QPO2ugehQ97-HXvdO4vgg/edit?usp=sharing

It was defined for the day before, but quick-plan didn’t schedule it for Wednesday. Two weeks later it was also scheduled and here everything worked fine.

**Comment by mgifos** [comment]
Sounds like a problem with asynchronous execution ... e.g. a definition of **6k @GA1/2+STL** has not  been completed before the scheduling of the first repetition has started. I'm gonna investigate this further by code staring.

**Comment by mgifos** [comment]
I managed to reproduce the issue. The bug is confirmed. The problem is if you try to schedule a workout defined in a same week again.

**Comment by leingang** [comment]
Thank you! I look forward to a new release so I can take advantage of this fix.

**Comment by mgifos** [comment]
Released in v0.2.4
