### ISSUE TITLE
Nothing gets imported... :(

### ISSUE THREAD

**Issue by f4hla** [mgifos/quick-plan#22]
Hi 
Here is my plan, I try to schedule and get all to null (best case) (or various random errors) -- HELP :) 
--- Command
./quick-plan schedule -n 2018-10-18 -x -e xxx@xxx.xxx -p XXX -v /Users/gilou/Dropbox/Maison/Sports/GARMIN_REUNION.csv2 -d
---Log
Successfully logged in to Garmin Connect

Deleting workouts:

Creating workouts:

Scheduling:

Statistics:
  0 deleted
  0 imported
  0 scheduled
Logged out and closed connection
Bye

---Plan (attached file as well)
[GARMIN_REUNION.txt](https://github.com/mgifos/quick-plan/files/2233712/GARMIN_REUNION.txt)

Week;Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday
1;;"running: VMA-Asc-15%
- warmup: 25:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5 
- repeat: 8
  - run: 0:45 @z5
  - recover: 0:30@z2
- recover: 3:00 @ z2
- repeat: 8
  - run: 0:45 @z5
  - recover: 0:30@z2
- run: 15:00@z2
- cooldown: lap-button";"running: 1hFond-Vallone-PPG
- run: 60:00 @z2
- cooldown: lap-button";"running: Seuil-EndActive-Vallone
- warmup: 30:00 @z2
- repeat: 2
  - run: 20:00@z3
  - recover: 4:00@z1
- run: 10:00@z2
- cooldown: lap-button";1h30Fond-Vallone-PPG;1h30Fond-Vallone-PPG;"running: Long-2h-750D+
- run: 120:00@z3
- cooldown: lap-button"
2;;"running: VMA-Faible-Aero
- warmup: 30:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5 
- repeat: 8
  - run: 300m@z4
  - recover: 100m@z3
- recover: 2:00@z2
- repeat: 8
  - run: 300m@z4
  - recover: 100m@z3
- run: 15:00@z2
- cooldown: lap-button";"running: 15kFond-Vallone-PPG
- run: 15000m@z2
- cooldown: lap-button";"running: Seuil-Nature
- warmup: 30:00 @z2
- run: 4000m@z4 
- recover: 3:00@z2
- run: 3000m@z4 
- recover: 3:00@z2
- run: 2000m@z4 
- recover: 3:00@z2
- run: 1000m@z4 
- run: 10:00@z2
- cooldown: lap-button";2hFond-Vallone-PPG;"1hFond-Vallone-PPG

1h30Fond-Vallone-PPG";"running: Long-2hvtt+1h30-500D+
- run: 90:00@z3
- run: 90:00@z2
- cooldown: lap-button"
3;;"running: VMA-Asc-fort%
- warmup: 25:00 @z2
- repeat: 10
  - run: 50m@z5 
  - recover: 50m@z2
- run: 10:00@z2
- cooldown: lap-button";1hFond-Vallone-PPG;"running: Seuil
- warmup: 30:00 @z2
- run: 15:00@z4 
- recover: 3:00@z2
- run: 10:00@z4 
- recover: 3:00@z2
- run: 5:00@z4 
- run: 15:00@z2
- cooldown: lap-button";2hFond-Vallone-PPG;1hFond-Vallone-PPG;"running: RandoTrail-4h-1.5kD+
- run: 240:00@z1
- cooldown: lap-button"
4;;"running: footing
- run: 45:00 @z1
- repeat: 5
  - run: 100m@z5 
  - recover: 20m@z2
- cooldown: lap-button

";1hFond-Vallone-PPG;"running: Sensation-Plat
-warmup: 20:00@z2
- repeat: 12
  - run: 0:30@z5
  - recover: 0:30@z1
- run: 10:00@z1
- cooldown: lap-button";;"running: Echauffement
- warmup: 15:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5 
- run: 10:00@z2
- cooldown: lap-button";"running: TestTrail-30k
- run: 240:00@z2
- cooldown: lap-button"
5;;"footing
";;;"running: Intensite-LegereDescente-Acc150%
- warmup: 30:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5
- repeat: 12
  - run: 150m@z5
  - recover: 150m@z1
- run: 15:00@z1
- cooldown: lap-button";1hFond-Vallone-PPG;15kFond-Vallone-PPG
6;;"running: VMA-Desc-fort%
- warmup: 25:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5 
- repeat: 10
  - run: 50m@z5 
  - recover: 50m@z2
- run: 10:00@z2
- cooldown: lap-button";"running: 1h30Fond-Vallone-PPG
- run: 90:00 @z2
- cooldown: lap-button";"running: Seuil-Cote
-warmup: 30:00@z2
- repeat: 4
  - run: 8:00@z4
  - recover: 2:30@z3
- run: 15:00@z1
- cooldown: lap-button";"running: 2hFond-Vallone-PPG
- run: 120:00 @z2
- cooldown: lap-button";1hFond-Vallone-PPG;"running: RandoTrail-1hprefat+2hrun-w-750D+
- run: 60:00@z3
- run: 120@z2
- cooldown: lap-button"
7;;"running: 1h
- run: 60:00 @z1
- cooldown: lap-button

running: VMA-trail
- run: 30:00 @z2
- repeat: 8
  - run: 3:00@z5 
  - recover: 1:00@z2
- run: 10:00 @z1
- cooldown: lap-button";1hFond-Vallone-PPG;"running: 1h15Fond-Vallone-Jeun
- run: 75:00 @z2
- cooldown: lap-button";2hFond-Vallone-PPG;1hFond-Vallone-PPG;"running: RandoTrail-5h-2.5kD+
- run: 300:00@z1
- cooldown: lap-button"
8;;"
";1hFond-Vallone-PPG;Sensation-Plat;;Echauffement;"running: TestTrail-50k
- run: 360:00@z2
- cooldown: lap-button"
9;;"footing
";;1hFond-Vallone-PPG;;"running: facile
- run: 45:00@z1
- cooldown: lap-button
";1hFond-Vallone-PPG
10;;"1h

running: End-Musc-Squat
- run: 25:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5 
- repeat: 10
  - run: 400m@z5 
  - recover: 0:30@z1
- run: 15:00 @z2
- cooldown: lap-button";15kFond-Vallone-PPG;"running: Seuil-Vallone
- warmup: 30:00 @z2
- repeat: 5
  - run: 6:00@z4
  - recover: 2:00@z2
- run: 15:00@z1
- cooldown: lap-button";"running: velo4hOuRenforcement
- run: 180:00 @z2
- cooldown: lap-button";"1hFond-Vallone-PPG

1h30Fond-Vallone-PPG";"running: RandoTrail-5h-2kD+
- run: 300:00@z2
- cooldown: lap-button"
11;;;"running: VMA-Courte-Aero
- warmup: 25:00 @z2
- repeat: 10
  - run: 100m@z1 
- repeat: 3
  - run: 100m@z5 
- repeat: 15
  - run: 200m@z5
  - recover: 100m@z1
- run: 10:00@z2
- cooldown: lap-button";1hFond-Vallone-PPG;;;2hFond-Vallone-PPG
12;;"running: Rappel-intensite
-warmup: 3000m@z2
- repeat: 10
  - run: 0:30@z5
  - recover: 0:30@z1
- cooldown: lap-button";;Echauffement;"running: TRAIL
- run:900:00@z1";;

**Comment by mgifos** [comment]
Your CSV file is not valid. You can validate it here: https://csvlint.io/

and this is the status of the validation I did on your file:
https://csvlint.io/validation/5b5b56cb2869ac0004000001

Did you edit your CSV manually? Which tool did you use to export?

**Comment by f4hla** [comment]
Hi, 
thanks for the reply, but I think there is something else (the validation report shows invalid csv due to the use of ';' iso ',').
Anyway, you can see the new simplifier csv here, pass with 0 error your link and still same result, nothing imported...
Any help?
Regards
[GARMIN_REUNION_Soir.txt](https://github.com/mgifos/quick-plan/files/2237765/GARMIN_REUNION_Soir.txt)


--
Successfully logged in to Garmin Connect

Deleting workouts:

Creating workouts:

Scheduling:

Statistics:
  0 deleted
  0 imported
  0 scheduled
Logged out and closed connection
Bye
--

**Comment by f4hla** [comment]
by the way, also getting this error randomly
[WARN] [07/28/2018 09:51:22.244] [quick-plan-akka.actor.default-dispatcher-12] [akka.actor.ActorSystemImpl(quick-plan)] Illegal header: Illegal 'server' header: Invalid input 'EOI', expected product or comment (line 1, column 1): 
^

**Comment by mgifos** [comment]
Hi, 
The last warning is ok, it's not an error. I'm not at home this weekend so I can only comment from my phone, but I'll check your file thoroughly on Monday. By then, please check of you have any special character in the workout names and be sure you are using the latest version of the software because the previous one only recognised "workout" keyword instead of "running" our "cycling". Supported characters of workout names are only those from ASCII table up to 128.

**Comment by f4hla** [comment]
Hi
thanks for your support (and enjoy the weekend ;))

I am using 0.2.3 release, so should be ok.
In the simplified file I just uploaded, no special char.

Thanks a  lot

**Comment by mgifos** [comment]
A short instruction  list till then. Try with a smaller portions of your plan, e.g. try specifying just a first week of your plan with a few simple workouts and simple names. Make sure the format of your spreadsheet is the same as the one in the example. I haven't use any other spreadsheet editor but the one from Google, so to be on the safe side, try first with that one and we can focus later on supporting the others.

**Comment by mgifos** [comment]
One more thing, I used this CSV parser:
https://github.com/tototoshi/scala-csv

It could be that the issue is even related to this library because from the output of the first version I noticed that it couldn't parse the CSV.

**Comment by f4hla** [comment]
Hi
ok - I was using csv export from M$ Excel...
I switched to Google Editor online then download as csv and...it works :)
Great!!
I guess then there maybe a few things added by xls. You may want to check but at least every one can now know that through Google online editor it works.
thanks (but I would appreciate a little test from inside using the previously posted file).
Regards

**Comment by mgifos** [comment]
In your first example of CSV, MS Excel enforces **\r** carriage return and Google editor enforces line feed **\n** as the line break character. I'll open another issue to support this.
