### ISSUE TITLE
Support openjdk 10

### ISSUE THREAD

**Issue by aleixq** [mgifos/quick-plan#27]
Thank's for this tool! Compiling or running it in arch with this openjdk jre:
```
$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13)
OpenJDK 64-Bit Server VM (build 10.0.2+13, mixed mode)
```
gives:
```
target/universal/stage/bin/quick-plan  

The java installation you have is not up to date
requires at least version 1.6+, you have
version 10.0.2

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .
```

I have no idea about scala, but the solution I found is increasing the sbt native packager  version as it's now solved  ( https://github.com/sbt/sbt-native-packager/issues/1145 ).
changing this line:
https://github.com/mgifos/quick-plan/blob/7ba9176db924775e547d82800df20cca55849791/project/plugins.sbt#L2
solves it .

**Comment by mgifos** [comment]
Thanks for noticing and pointing out where the problem was. It's fixed in sbt-native-packager:1.3.6, so I used this dependency version to fix the bug.
