### ISSUE TITLE
Convert plan to ical

### ISSUE THREAD

**Issue by aleixq** [mgifos/quick-plan#31]
Just to let you know, I have created a python utility in gitlab ( https://gitlab.com/aleixq/quick-plan-ical ) to convert training plans to ical (garmin discards all the description when exporting ical). I have used the same csv plan definition.
This way a plan can be used in a standard calendar application.

Thank's!
(sorry to create an issue)

**Comment by mgifos** [comment]
Nice, btw the link doesn't work for me

**Comment by aleixq** [comment]
oops... It's public now.
