### ISSUE TITLE
Nested repeats are not accepted

### ISSUE THREAD

**Issue by othmanebekkari** [mgifos/quick-plan#38]
Seems like workout with nested repeats are not accepted. Example:
```
running: r11k-2*4*0.6@4:20
- warmup: 20:00
- repeat: 2
  - repeat: 4
    - run: 0.6km @ 4:25-4:15 mpk
    - recover: 1:00
  - recover: 05:00
- cooldown: lap-button
```

**Comment by mgifos** [comment]
Can you do this through GarminConnect UI? I don't see a way to create nested repeats.

![image](https://user-images.githubusercontent.com/7441431/49810113-c2b30500-fd60-11e8-993f-89f226230f0f.png)

**Comment by mgifos** [comment]
Ah I managed to this by dragging another repeat into the first one. I'll leave the issue open, it's definitely something I didn't know it was even possible.

**Comment by mgifos** [comment]
Try nested repeats with release 0.3.3
