### ISSUE TITLE
Delete Training Plan

### ISSUE THREAD

**Issue by JCPvanHooren** [mgifos/quick-plan#45]
Would it be possible to add an option to Delete all existing workouts with same names as the ones that are going to be imported, without actually importing?

It's probably as cumbersome to delete workouts from Garmin as it is to add them. This is where this tool is awesome. However, I'd want to keep my different training plans together in a sheet and import them when needed. It'd be awesome if I could then also quickly delete all related workouts from Garmin to clean up the list of workouts there, without re-importing or scheduling them.

**Comment by mgifos** [comment]
Yes, you can do it by using option -x (don't use import or schedule, just -x)

**Comment by JCPvanHooren** [comment]
Awesome.
Might be useful to add in help.
Thanks! both for the quick response as well as building this utility.

**Comment by mgifos** [comment]
Right. I planned to add some more useful examples that will make the usage more easier.
