### ISSUE TITLE
Last week of 12 workouts does not get scheduled...

### ISSUE THREAD

**Issue by EELien** [mgifos/quick-plan#55]
First things first: I absolutely loooove this project!
I'd be happy to make a small donation somewhere... just say the word. :-)

Took me some time to grok it, but now I'm able to upload and schedule workouts. 

One question: my raceday is on januari 5th. 
All workouts are scheduled correctly, except the very last week (dec 23th) of training.

I have no clue what goes wrong or what my mistake might be...
Can you help me out? Thanks!

WHAT I PUT ON THE COMMAND LINE:  
C:\Users\Connie.ConnieZen\Dropbox\Hardlopen\2020 Ultramaatjes\Nerdy dingetjes\Quick Plan\quick-plan-0.3.5\bin\quick-plan.bat schedule -s 2019-10-07 -x -c -e xxxxxx.xxx@gmail.com -p Xxxx99 Testschema4.csv

THE FILE "TESTSCHEMA4.CSV":
Week,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
1,"running: 8k jog
- run: 8km @z1",,6k vlot,,"running: 10k jog
- run: 10km @z1",,"running: 22k jog
- run: 22km @z1
2,"running: 8k jog
- run: 8km @z1",,"running: 8k vlot
- run: 8km @z2",,8k jog,,"running: 12k jog
- run: 12km @z1"
3,,,6k jog,,,"running: 30k testloop
- run: 30km",
4,,,8k jog,,8k jog,,22k jog
5,8k jog,,6k jog,,8k jog,,"running: 24k jog
- run: 24km @z1"
6,8k jog,,6k vlot,,6k jog,,"running: 32k jog
- run: 32km @z1"
7,8k jog,,8k vlot,,8k jog,,"running: 28k jog
- run: 28km @z1"
8,8k jog,,8k vlot,,8k vlot,,16k jog
9,8k jog,,8k vlot,,8k vlot,,24k jog
10,8k jog,,"running: 12k vlot
- run: 12km @z2",,6k jog,,20k jog
11,"running: 12k jog
- run: 12km @z1",,,,,,"running: 40k testloop
- run: 40km"
12,,,6k jog,,6k vlot,,20k jog

**Comment by mgifos** [comment]
instead of -s (start day of the training plan), try to use -n (as end day of the plan). The command line options states in the last sentance: "#Schedules ultra 80k plan targeting 28-4-2018 for a race day, while previously deleting if any with the same name already exists
quick-plan schedule -n 2018-04-29 -x -e your-mail-address@example.com ultra-80k-runnersworld.csv"

**Comment by EELien** [comment]
Thank you!

Kind regards, Connie


Op do 10 okt. 2019 om 22:10 schreef Nikola Petkov <notifications@github.com
